#
# This config.toml is an example and based on the ananke theme
# https://github.com/theNewDynamic/gohugo-theme-ananke/.
#
# If you use a different theme, you might need to change the content of config.toml
# to your liking.
#

#
# Theme setup
#
# If you use go mod to install your theme, you must use the URL of the theme.
# If your theme is in the themes directory, you just need to specify its name.
#
#theme = "ananke"
theme = ["github.com/RoneoOrg/hugo-remix-one-click-netlify-cms"]

baseURL = 'https://daytongo.club'
languageCode = 'en-us'
defaultContentLanguage = 'en'


[params]
  title = 'Dayton Ohio Go Club'
  metaDescription = "A Local Go (also known as Baduk) Club that meets up in the Dayton Ohio Area"


# Languages
[Languages.en]
languageName = "En"
languageCode = "en-us"
contentDir = "content/english"
weight = 1
mark = "EN"

[Languages.fr]
languageName = "fr"
languageCode = "fr-fr"
contentDir = "content/fr"
weight = 2
mark = "FR"


[taxonomies]
  category= "theme"
  scene = "scenes"
